[package]
name = "physics"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.2"
cgmath = { version = "0.18.0", features = ["swizzle"] }
eframe = { version = "0.21.3", features = ["wgpu"] }
encase = { version = "0.4.1", features = ["cgmath"] }
memoffset = "0.8.0"
rayon = "1.6.1"
